"""
Notion Database Schema Definition for Literature Summary

This module defines the schema for the Notion database that stores
literature summaries generated by cmp_summarizer.

## Setup Instructions:
1. Create a new Database in Notion (or use an existing one)
2. Add the following properties to match this schema:
   - Hash ID (Text) - Unique identifier
   - Authors (Text)
   - Journal (Text)
   - Year (Number)
   - Keywords (Multi-select)
   - File Path (Text)
   - Last Modified (Date)
   - Title (Title) - Default title column
3. Share the database with your Notion Integration
4. Copy the Database ID to .env file
"""

NOTION_SCHEMA = {
    "Title": {
        "type": "title",
        "description": "Paper title (auto-extracted from markdown)"
    },
    "Hash ID": {
        "type": "rich_text",
        "description": "SHA256 hash as unique identifier"
    },
    "Authors": {
        "type": "rich_text",
        "description": "Author list"
    },
    "Journal": {
        "type": "rich_text",
        "description": "Journal name"
    },
    "Year": {
        "type": "number",
        "description": "Publication year"
    },
    "Keywords": {
        "type": "multi_select",
        "description": "Keywords from the paper",
        "options": {
            "colors": [
                "blue", "brown", "green", "orange", "pink", "purple",
                "red", "yellow", "gray", "default"
            ]
        }
    },
    "File Path": {
        "type": "rich_text",
        "description": "Relative path to the markdown file"
    },
    "Last Modified": {
        "type": "date",
        "description": "Last modification date of the markdown file"
    }
}


def get_property_payload(name: str, value, prop_type: str = None) -> dict:
    """
    Convert a property value to Notion API payload format.

    Args:
        name: Property name
        value: Property value
        prop_type: Property type (auto-detected if None)

    Returns:
        Dict in Notion API property format
    """
    if prop_type is None:
        prop_type = NOTION_SCHEMA.get(name, {}).get("type", "rich_text")

    if prop_type == "title":
        return {
            "title": [
                {
                    "text": {
                        "content": str(value) if value else ""
                    }
                }
            ]
        }
    elif prop_type == "rich_text":
        return {
            "rich_text": [
                {
                    "text": {
                        "content": str(value) if value else ""
                    }
                }
            ]
        }
    elif prop_type == "number":
        return {
            "number": int(value) if value else None
        }
    elif prop_type == "date":
        return {
            "date": {
                "start": value
            } if value else None
        }
    elif prop_type == "multi_select":
        if isinstance(value, str):
            # Parse comma-separated string
            keywords = [k.strip() for k in value.split(",") if k.strip()]
        elif isinstance(value, list):
            keywords = value
        else:
            keywords = []

        return {
            "multi_select": [
                {"name": kw} for kw in keywords
            ]
        }

    return {"rich_text": [{"text": {"content": str(value)}}]}
